language: java
install: skip
os: linux
services:
  - postgresql
jdk:
  - openjdk11
before_script:
  - psql -c 'create database esadb_test;' -U postgres
  - psql -c 'create user esa_test;' -U postgres
script:
  - ./gradlew build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email:
    recipients:
      - chandan@technogise.com
      - aamir@technogise.com
      - satyam@technogise.com
      - shubhamsahu@technogise.com
    on_success: never
    on_failure: always
